import './globals.css'
import MainNavigation from '../components/MainNavigation/MainNavigation'
import SlimNavigation from '../components/SlimNavigation/SlimNavigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <SlimNavigation />
          <MainNavigation />
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
