import './globals.css'
// pages/_app.js
import { Roboto } from 'next/font/google'
// If loading a variable font, you don't need to specify the font weight
const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

import MainNavigation from '../components/MainNavigation/MainNavigation'
import SlimNavigation from '../components/Navigation/SlimNavigation'
import SlimFooter from '../components/Footers/SlimFooter/SlimFooter'
import NormalMenu from '../components/Navigation/NormalMenu'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <SlimNavigation />
          <NormalMenu />
        </header>
        <main>{children}</main>
        <SlimFooter />
      </body>
    </html>
  )
}
